# Generated by Django 3.0.5 on 2020-06-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_visitormodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitormodel',
            name='owner_flag',
            field=models.CharField(default='False', max_length=5),
        ),
    ]
