# Generated by Django 3.0.5 on 2020-06-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_visitormodel_owner_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitormodel',
            name='time_visit',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
